#version of docker-compose syntax
version: "3.9"

#one or more service needed for our application
#name of service - app; context in current directory
#ports of local machine : ports of docker container
#volumes - mapping of dir from sys to docker container
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"